### ISSUE TITLE
The edited experimental parameters were not saved

### ISSUE THREAD

**Issue by JoeanAmier** [Crop-Phenomics-Group/SeedGerm#1]
After adding the experiment, edit the experiment and modify the parameters. The modified parameters are not saved to the JSON file. After restarting the software, the parameters of the experiment are the parameters before modification.

I tried to modify the name of the experiment parameters and the end image. After clicking the confirm button, I can see that the name of the experiment has changed in the GUI, but the parameters of the end image have not changed. After restarting the software, the parameters are the same as before.

The file named editexperiment.py did not find the code to save the new data to the JSON file.

**Comment by JoeanAmier** [comment]
After modifying the name of the experiment, a new folder will be created in the folder data, but it is not saved in the JSON file.

**Comment by gashion** [comment]
I just saw this - please email Josh.colmer@earlham.ac.uk for technical questions.
